Fix translation issue
xlmnxp/blue-recorder-rs pull request #71
Opened 2024-06-06 21:07 UTC by ochibani

The translation need more review.

2024-06-18 04:06 UTC, ochibani commented
area_set_button.connect_clicked(move |_| {
        _area_capture
            .borrow_mut()
            .get_window_by_name(&gettext("Area Chooser"));
Forgot to replace this line.

2024-06-18 04:12 UTC, ochibani commented
_area_capture
            .borrow_mut()
            .get_window_by_name(_area_chooser_window.title().unwrap().as_str());
This should solve the issue.

2024-08-08 08:42 UTC, hamirmahal commented on README.md
> +It based on [Green Recorder](https://github.com/mhsabbagh/green-recorder) and rewritten in Rust with improvements.
```suggestion
This project is based on [Green Recorder](https://github.com/mhsabbagh/green-recorder) and rewritten in Rust with improvements.
```

2024-08-08 08:44 UTC, hamirmahal requested changes

2024-08-08 08:44 UTC, hamirmahal commented on README.md
> +It based on [Green Recorder](https://github.com/mhsabbagh/green-recorder) and rewritten in Rust with improvements.
```suggestion
This project is based on [Green Recorder](https://github.com/mhsabbagh/green-recorder) and is rewritten in Rust with improvements.
```

2024-08-08 08:44 UTC, hamirmahal commented on README.md
> +Blue Recorder available as Snap and Flatpak package:
```suggestion
Blue Recorder is available as a Snap and Flatpak package.
```

2024-08-08 08:44 UTC, hamirmahal commented on README.md
> +Blue Recorder depend in the following dependencies:
```suggestion
Blue Recorder depends on the following dependencies:
```

2024-08-08 08:44 UTC, hamirmahal commented on README.md
> +Install dependencies Ubuntu and Debian based distros:
```suggestion
Install dependencies for Ubuntu and Debian-based distros:
```

2025-07-15 12:54 UTC, ochibani commented
To-do list:
* Fix window recording in X11 (ffmpeg record area only; I suggest using gstreamer instead).
* Fix issues in Wayland recording (didn't work for me).
* Update blue_recorder_core repo.
* Disable GUI when follow mouse is active (we should review when buttons should be active/inactive).
* Return Run Command feature with error handling.
* Test on Windows platform.
* Test on FreeBSD platform.
* Update README (Windows & FreeBSD building guide).
* Update Snap package.
* Update Flatpak package.

Notes:
- Recording sound & video separately makes merging large files very laggy. 
- I added some features, like showing area, but never tested them.

Good luck!

2026-06-13 09:07 UTC, merged